### ISSUE TITLE
Option to set images to be visible only by logged-in users

### ISSUE THREAD

**Issue by EmberHeartshine** [mdshack/shotshare#23]
Just a feature request to create private images, accessible only to users who are logged in to view an image, even if linked directly. (maybe not the direct image link, but at minimum the image view page.) This option should ideally be toggleable after upload, to make an image private that was public or vice-versa without deleting it.

**Comment by mdshack** [comment]
This functionality has just been rolled out with the latest release 1.9.1!

A note here, we currently set everything in the uploads folder as publicly accessible, meaning the images in the uploads folder will not have any authentication, this change only impacts what has commonly been referred to as the "Share" page, or the one at `/shots/{id}`. If we see a direct need for authenticating at the actual direct link level, that will be a fairly large undertaking, feel free to pop an issue for it though.

![image](https://github.com/mdshack/shotshare/assets/37004539/6fdb352c-2a77-4e28-9246-25875a9151ec)
