### ISSUE TITLE
Delete images uploaded by "me"

### ISSUE THREAD

**Issue by EmberHeartshine** [mdshack/shotshare#24]
Feature request to allow the logged-in user to delete an image if they were the one who uploaded it.

**Comment by mdshack** [comment]
![image](https://github.com/mdshack/shotshare/assets/37004539/94dcc575-dc58-473e-ab43-f838c7df3044)

Currently working on improvements to the shot view, this (ability to delete your shots) should be captured in that, also looking at 

- Adding titles
- Adding reactions (upvote/downvote), might make this an opt-in feature

Hopefully, I should have this out in the next feature release (1.7.0). Let me know if you have any feedback on any of this!

**Comment by EmberHeartshine** [comment]
I will definitely say the up/downvotes should be opt-in. I've personally never been a fan of social-media-ifying image hosts.

**Comment by mdshack** [comment]
> I will definitely say the up/downvotes should be opt-in. I've personally never been a fan of social-media-ifying image hosts.

I have added a feature flag so you can "opt in" to the reactions stuff!

**Comment by mdshack** [comment]
This has just been rolled out in 1.7.0, lemme know if you have any questions on this!
