### ISSUE TITLE
Remove specific share links for uploaded images

### ISSUE THREAD

**Issue by EmberHeartshine** [mdshack/shotshare#25]
If, for example, I only want the shots page and direct links visible, I'd like to be able to turn the rest of the generated links off (or hide them).

**Comment by mdshack** [comment]
> If, for example, I only want the shots page and direct links visible, I'd like to be able to turn the rest of the generated links off (or hide them).

Added new configuration options [here](https://github.com/mdshack/shotshare?tab=readme-ov-file#configuration-options), this functionality will be live in 1.6.0 which should go out later today.
