### ISSUE TITLE
Better way to indicate that a shot's title is editable

### ISSUE THREAD

**Issue by EmberHeartshine** [mdshack/shotshare#35]
I'm not sure where [f71c756](https://github.com/mdshack/shotshare/commit/f71c756af1ad7ca692bd99bea6de2deea935306e) went wrong, but the edit title functionality does not appear to work. This is true both for sets and for individual shots.

![image](https://github.com/mdshack/shotshare/assets/50666308/e9bd4577-2a8a-465d-8a38-33778eaafa93)

**Comment by EmberHeartshine** [comment]
Doesn't look like I have any error/exception logs in `/app/storage/logs/`. Is there somewhere else I could look?

**Comment by mdshack** [comment]
> Doesn't look like I have any error/exception logs in `/app/storage/logs/`. Is there somewhere else I could look?
> 
> **Edit:** OHHH, I see. I didn't realize that you could just click on the name. The lack of the visible pencil icon threw me off. You could close this if that's the intended behavior or possible change it to an enhancement request to add the pencil icon to unnamed shot pages.

Indeed, I know I had shot the original image with the pencil icon, but I thought this might've been a bit cleaner. 

There might be a better way to indicate that as being an editable field, I had also played around with the ghost button variant for that, but it threw the padding off and looked a bit wonky, also the pencil is still an option, open to any additional suggestions too.

**Comment by EmberHeartshine** [comment]
To be fair, I think since there's a separate icon for Delete as well, the pencil icon isn't super obtrusive. It's only visible to the logged-in user anyway.

Oh, just now I did find a bug: logged-out users can (locally only; it doesn't actually save) the title since the field is an input box.

![image](https://github.com/mdshack/shotshare/assets/50666308/634688c6-e32a-4386-b410-df6b3c644c9d)

(above is from a Private window with no login; the original caption looked like the below)

![image](https://github.com/mdshack/shotshare/assets/50666308/a27c3834-8dcd-466b-9899-2aece6a47fbf)

Perhaps the field should have `readonly="true"` or `disabled="disabled"` set on it for a logged-out user.

**Comment by mdshack** [comment]
> To be fair, I think since there's a separate icon for Delete as well, the pencil icon isn't super obtrusive. It's only visible to the logged-in user anyway.
> 
> Oh, just now I did find a bug: logged-out users can (locally only; it doesn't actually save) the title since the field is an input box.
> 
> ![image](https://private-user-images.githubusercontent.com/50666308/296648726-634688c6-e32a-4386-b410-df6b3c644c9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNTAzMTcsIm5iZiI6MTcwNTM1MDAxNywicGF0aCI6Ii81MDY2NjMwOC8yOTY2NDg3MjYtNjM0Njg4YzYtZTMyYS00Mzg2LWI0MTAtZGY2YjNjNjQ0YzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDIwMjAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNGFiYmNmNmYzZjRjYjQ0NWQ1NDdkMjdmMjU1ZTI0M2YzYTBiNDY5YjcxNzkwMzAwNmJhNjdkNTAxZjNiZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HgYUfNJTQdAn5IX4MgSEhPag8ldyy8ggQc8fQw-MQlg)
> 
> (above is from a Private window with no login; the original caption looked like the below)
> 
> ![image](https://private-user-images.githubusercontent.com/50666308/296648849-a27c3834-8dcd-466b-9899-2aece6a47fbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNTAzMTcsIm5iZiI6MTcwNTM1MDAxNywicGF0aCI6Ii81MDY2NjMwOC8yOTY2NDg4NDktYTI3YzM4MzQtOGRjZC00NjZiLTk4OTktMmFlY2U2YTQ3ZmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDIwMjAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDc3NzFiMjEzYzhlYTdkYzQ4N2EyNDE4M2YzZmQ5NzNmZWYxMGZhNTE5NzcxZjhjMTIzMjI5YjcyNjM3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l8bLz6NE9N34VV_emQklcvXqcRu6ASHUf-L2HFyZ2aI)
> 
> Perhaps the field should have `readonly="true"` or `disabled="disabled"` set on it for a logged-out user.
> 
> **Edit:** I didn't actually look at the HTML before posting. Oops. It looks like the `h1` tag has a `contenteditable` attribute set to null; for logged-out users it should probably be `contenteditable="false"`. (Just tested locally using Inspect Element and this works as expected.)

Good catch on that being editable by guests, I just popped a fix for that, so we should see that fix in the next release.

**Comment by mdshack** [comment]
@EmberHeartshine Do you think this would be more clear?

![image](https://github.com/mdshack/shotshare/assets/37004539/e58b3b5a-0e50-4a6e-bbc0-20dfc4e4dd19)

- Added back the pencil icon, the header is still clickable, but the pencil icon will just focus the element (2 ways to edit the title)
- Added this popover that will show when you are editing to indicate press "enter" to save

**Comment by EmberHeartshine** [comment]
Yes, that's perfect!

**Comment by mdshack** [comment]
This functionality has just been rolled out with the latest release 1.9.1!

![image](https://github.com/mdshack/shotshare/assets/37004539/c0c139ac-6f10-4568-9a42-d8f07e3caf47)
