### ISSUE TITLE
Ability to hide/privatize uploader name

### ISSUE THREAD

**Issue by EmberHeartshine** [mdshack/shotshare#36]
Not a priority for me, but I imagine some users may want a way to upload pseudo-anonymously (eg. they still have to log in to upload, but can hide the name of their account on the shots page).

**Comment by mdshack** [comment]
Thanks for capturing this, this was on the radar but hadn't put it into an issue yet.

**Comment by EmberHeartshine** [comment]
Alongside #32, the designated admin accounts should be able to see uploader names even if they've been hidden.

**Comment by mdshack** [comment]
This functionality has just been rolled out with the latest release 1.9.1! 

![image](https://github.com/mdshack/shotshare/assets/37004539/d778b92a-1463-4ebf-9777-6fbad016d976)
![image](https://github.com/mdshack/shotshare/assets/37004539/224dda81-73b5-431d-af83-790426cd4c97)
