### ISSUE TITLE
Deleted images is still be accessable via direct link

### ISSUE THREAD

**Issue by ai-ri-kr** [mdshack/shotshare#41]
A deleted image should be like that, deleted. The image should not still be stored on the server after deletion. Please fix.

Also, please add a command that allows you to clear deleted images only.

**Comment by EmberHeartshine** [comment]
Can confirm, just tested. Not sure if there's a cleanup task or what but the images are still on the disk and accessible by direct link. Deleting the image file obviously fixes it.

**Comment by mdshack** [comment]
Thanks for raising this issue, I popped a fix for this [here](https://github.com/mdshack/shotshare/commit/e9bbadd6c0b6c0a92dcb55d33e0a7dc9b515b554). We will see this go out in the next release (1.9.0), and I will update here when that is rolling out.

**Comment by ai-ri-kr** [comment]
Very nice! What I saw, 1.9.0 will only add deletion of the file and now adding a new command (`shotshare:clean-deleted-images`), correct?

**Comment by mdshack** [comment]
> Very nice! What I saw, 1.9.0 will only add deletion of the file and not add a new command (`shotshare:clean-deleted-images`), correct?

Since this was a bug I am not sure adding a command to handle a condition that shouldn't be in the future is the correct move, I might do a migration to handle this but there might be a better way to handle this, lemme think on it for a bit.

**Comment by mdshack** [comment]
> Very nice! What I saw, 1.9.0 will only add deletion of the file and not add a new command (`shotshare:clean-deleted-images`), correct?

I ended up adding an `--only-missing` flag to the existing clean images command.

**Comment by mdshack** [comment]
This functionality has just been rolled out with the latest release 1.9.1!
