### ISSUE TITLE
419 Page expired

### ISSUE THREAD

**Issue by ai-ri-kr** [mdshack/shotshare#44]
I have `mod_headers` enabled for my Apache server and the configuration below gives me `419 Page expired` when I try to use any form with the module enabled.

Is there any solution that I can use even when `mod_headers` is enabled? I have searched the internet for a few days and tried some possible solutions (can't remember which ones) and have now given up. Posting this issue is my "only" chance to fix this. And with "only" I mean that I haven't seen every single solution out there xD

```
Define E my@email.com
Define P 80004

Protocols h2 h2c http/1.1

<VirtualHost *:80>
  ServerAdmin ${E}
  ServerName img.airikr.me

  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:${P}/
  ProxyPassReverse / http://127.0.0.1:${P}/

  RewriteEngine On
  RewriteCond %{SERVER_NAME} =img.airikr.me
  RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
  ServerAdmin ${E}
  ServerName img.airikr.me

  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:${P}/
  ProxyPassReverse / http://127.0.0.1:${P}/

  ErrorLog ${APACHE_LOG_DIR}/img.airikr.me.error.log

  RewriteEngine On

  SSLCertificateFile /.../img.airikr.me/fullchain.pem
  SSLCertificateKeyFile /.../img.airikr.me/privkey.pem
  Include /.../options-ssl-apache.conf
</VirtualHost>
```

**Comment by KevinGuest** [comment]
419 is normally a CSRF Token issue.

Hopefully this answer helps from Stack.
https://stackoverflow.com/questions/52583886/post-request-in-laravel-error-419-sorry-your-session-419-your-page-has-exp?rq=4

**Comment by ai-ri-kr** [comment]
Thanks, but adding `-e SESSION_DRIVER=file -e SESSION_DOMAIN=img.airikr.me -e SESSION_SECURE_COOKIE=true` to the `docker run` command didn't fix the issue. Same for `SESSION_SECURE_COOKIE=false` and when I removed `-e SESSION_DRIVER=file -e SESSION_SECURE_COOKIE=true` and only leaved `SESSION_DOMAIN` untouched.

The rest of the answers is for JavaScript or other stuff that must be added inside the actual source code. Didn't bother to do anything with that part :)

**Comment by EmberHeartshine** [comment]
Is it a Caddy 419 or an Apache 419?

**Comment by ai-ri-kr** [comment]
Apache 419. I use "Run in HTTP mode" with `-e FORCE_HTTPS=true`.

**Comment by EmberHeartshine** [comment]
I'm not super familiar with Apache in general, but what is mod_headers being used to do here?

And I don't think that really makes sense... Apache doesn't generate a 419 Page-Expired, Apache's 419 error is [Insufficient-Space-On-Resource](https://hc.apache.org/httpcomponents-core-4.4.x/current/httpcore/apidocs/org/apache/http/HttpStatus.html#SC_INSUFFICIENT_SPACE_ON_RESOURCE). 419 Page-Expired is a Laravel/Caddy error.

**Comment by ai-ri-kr** [comment]
Thank you for the information. I will get back to you after I got some sleep. Am very sleepy xD

**Comment by ai-ri-kr** [comment]
Alright! I use `mod_headers` to hardening my web server and strength the security of it. I use the following guides:

- https://geekflare.com/apache-web-server-hardening-security/
- https://www.tecmint.com/apache-security-tips/
- https://www.acunetix.com/blog/articles/10-tips-secure-apache-installation/

So the 419 error is Laravel/Caddy and not Apache after all? Then I have no clue of how to fix this issue :( I don't have any knowledge at all of Caddy nor Laravel (more than Laravel is PHP based).

I will ask someone to help me with all this, or if I have the mental strength to search the net for a solution.

Thank you for your help :)

**Comment by EmberHeartshine** [comment]
While looking up information about this for nginx, I stumbled over [this SO answer](https://stackoverflow.com/a/63242491) which kind of explains the issue entirely! So in your apache config you'll need to include `SameSite=none` in the cookie line.

**Comment by ai-ri-kr** [comment]
Oho! But what cookie line? I don't have any in my configuration file for my domain.

**Comment by EmberHeartshine** [comment]
Number 10 on [this page](https://geekflare.com/apache-web-server-hardening-security/) describes setting a cookie to handle the header setting. You'd need to set a cookie anyway for this kind of security to work either way.

**Comment by ai-ri-kr** [comment]
Aha, ok :) I'm sorry, can't think straight now.

I added `Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure` below `ProxyPassReverse` for both `*:80` and `*:443` in the config file for my domain and reloaded Apache. Same issue.

**Comment by EmberHeartshine** [comment]
After `Secure` set `;SameSite=none`

**Comment by ai-ri-kr** [comment]
Here's the line in `apache.conf` now: `Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure;SameSite=none`

Same issue.

**Comment by EmberHeartshine** [comment]
Sadly I've already overextended my knowledge here. I will say that nginx's `proxy_cookie_flags ~ secure;` worked for me but I'd imagine you don't want to learn a whole new server just for this.

**Comment by ai-ri-kr** [comment]
I am sort of interested in switching to nginx, but that's when I am ready for it.

Many thanks for your help anyway :) You have guided me to the right path (I hope) so I will dig deeper into this when my brain is more cooperative.

**Comment by ai-ri-kr** [comment]
This issue has now been solved. I tried to comment out `Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure;SameSite=none` and restarted Apache and everything just worked!
