### ISSUE TITLE
Image preview embed for Discord et. al.

### ISSUE THREAD

**Issue by EmberHeartshine** [mdshack/shotshare#46]
Title. Many image hosts have an embed that serves the image if it's linked on a service that's capable of displaying URL previews like Discord, Twitter, etc). I don't know what would go into this from a technical standpoint but it would be nice to have.

**Comment by mdshack** [comment]
Spent a fair bit of time testing on this, no matter what meta tags I tried, I _was not_ able to get Discord displaying these images from the shot view, will revisit this soon though and see if I can figure it out.

**Comment by EmberHeartshine** [comment]
Even `<meta property="og:image" content="[image links]">` ?

**Comment by mdshack** [comment]
Indeed @EmberHeartshine, [here's](https://github.com/mdshack/shotshare/pull/48/files#diff-9c4d234a265f0db90fe6d0bf235a1d73e0e064c57fece16bbc5ad817438e69f4R34-R40) some of the tags I tried.

**Comment by EmberHeartshine** [comment]
I'm not familiar with vue formatting, is the colon before `content` removed when processing for the client?

**Comment by mdshack** [comment]
> I'm not familiar with vue formatting, is the colon before `content` removed when processing for the client?

Correct, `:` indicates an expression as opposed to a static value

**Comment by bentasker** [comment]
The reason that the changes above don't work is that they rely on javascript injecting the tags. Most metdata scrapers don't render pages, they just fetch the base HTML and look for tags.

This PR should do what's needed: https://github.com/mdshack/shotshare/pull/62

**Comment by mdshack** [comment]
> The reason that the changes above don't work is that they rely on javascript injecting the tags. Most metdata scrapers don't render pages, they just fetch the base HTML and look for tags.
> 
> This PR should do what's needed: #62

Good catch and thank you for opening a PR!
