### ISSUE TITLE
Blank home page

### ISSUE THREAD

**Issue by amenolo** [mdshack/shotshare#49]
Using a http instance (latest release) is resulting in a blank page, both behind Nginx Proxy Manager with default config - which is otherwise working fine - and in case of direct access.

Same wih release 1.9.0 behind Nginx Proxy Manager only.

Browser independent. Any hints? Thanks!

![image](https://github.com/mdshack/shotshare/assets/29974944/2717ba24-a6d0-48f7-97b9-b0a43568d34a)
---
![image](https://github.com/mdshack/shotshare/assets/29974944/475ccc77-3532-47cf-bf5a-0612fece1a2c)
---

**Comment by mdshack** [comment]
> Using a http instance (latest release) is resulting in a blank page, both behind Nginx Proxy Manager with default config - which is otherwise working fine - and in case of direct access.
> 
> Same wih release 1.9.0 behind Nginx Proxy Manager only.
> 
> Browser independent. Any hints? Thanks!
> 
> ## ![image](https://private-user-images.githubusercontent.com/29974944/317844918-2717ba24-a6d0-48f7-97b9-b0a43568d34a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTk5MjUsIm5iZiI6MTcxMjUxOTYyNSwicGF0aCI6Ii8yOTk3NDk0NC8zMTc4NDQ5MTgtMjcxN2JhMjQtYTZkMC00OGY3LTk3YjktYjBhNDM1NjhkMzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE5NTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhY2FhNmU0ZGEzMzI0NTU1MWQ4NWQ3NjRlZmYxM2UzZjhjOGE3NTU2MTQ5MDk1ZjQzZjZmMGYyNmYzMWZjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HrKZ41OPYAHzTIUxYcHqsGF4RTvjvDwiMcBv14QxZqw)
> ## ![image](https://private-user-images.githubusercontent.com/29974944/317845143-475ccc77-3532-47cf-bf5a-0612fece1a2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTk5MjUsIm5iZiI6MTcxMjUxOTYyNSwicGF0aCI6Ii8yOTk3NDk0NC8zMTc4NDUxNDMtNDc1Y2NjNzctMzUzMi00N2NmLWJmNWEtMDYxMmZlY2UxYTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE5NTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMTI4N2RiNWQyZjA5OGQxNmQwOTZkNDk3YjI0NDI3NmE0ZDc5MjE2MGQ2MWU3YTMxNzFhOThjNjgxYWM3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hJ75_F7_CBWK5uQkPWDqWo9ogRwMdt2kWKjHvq0NxBE)

Are you getting any logs inside the container or in your browser?

**Comment by amenolo** [comment]
After further testing I noticed that issue seems to only occur with Nginx Proxy Manager HTTPS server block on and set as following:

![image](https://github.com/mdshack/shotshare/assets/29974944/cd4b572e-a94c-49c7-9cb5-cc2ad901555a)

---

Docker startup log:

```
   INFO  Nothing to migrate.  
Caching application configuration
   INFO  Configuration cached successfully.  
[08-Apr-2024 20:56:52] NOTICE: fpm is running, pid 18
[08-Apr-2024 20:56:52] NOTICE: ready to handle connections
INF ts=1712609812.873849 msg=using provided configuration config_file=/etc/caddy/Caddyfile config_adapter=
WRN ts=1712609812.8750105 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile file=/etc/caddy/Caddyfile line=2
INF ts=1712609812.875975 logger=admin msg=admin endpoint started address=localhost:2019 enforce_origin=false origins=["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]
WRN ts=1712609812.8762238 logger=http.auto_https msg=server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server server_name=srv0 http_port=80
INF ts=1712609812.8766096 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc0001d0080
INF ts=1712609812.8766875 logger=http.log msg=server running name=srv0 protocols=["h1","h2","h3"]
WRN ts=1712609812.8767629 logger=tls msg=unable to get instance ID; storage clean stamps will be incomplete error=open /data/caddy/instance.uuid: no such file or directory
INF ts=1712609812.8769293 msg=autosaved config (load with --resume flag) file=/config/caddy/autosave.json
INF ts=1712609812.8769367 msg=serving initial configuration
INF ts=1712609812.8819158 logger=tls msg=cleaning storage unit storage=FileStorage:/data/caddy
INF ts=1712609812.8821518 logger=tls msg=finished cleaning storage units
```
---

Docker log upon home page loading:

```
INF ts=1712609843.4329681 logger=http.log.access msg=handled request request={"remote_ip":"172.17.0.1","remote_port":"42482","client_ip":"172.17.0.1","proto":"HTTP/1.1","method":"GET","host":"shot.[redacted]","uri":"/","headers":{"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Connection":["close"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Dest":["document"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; rv:122.0) Gecko/20100101 Firefox/122.0"],"Cookie":[],"X-Real-Ip":["192.168.1.1"],"X-Forwarded-For":["192.168.1.1"],"X-Forwarded-Host":["shot.[redacted]"],"Accept-Language":["en-US,en;q=0.5"],"Accept-Encoding":["gzip, deflate, br"],"Sec-Fetch-Site":["none"]}} bytes_read=0 user_id= duration=0.098717598 size=8121 status=200 resp_headers={"Content-Encoding":["gzip"],"Server":["Caddy"],"Vary":["X-Inertia","Accept-Encoding"],"Set-Cookie":[],"Date":["Mon, 08 Apr 2024 20:57:23 GMT"],"Content-Type":["text/html; charset=UTF-8"],"Link":["<http://shot.[redacted]/build/assets/app-f4b307cb.css>; rel=\"preload\"; as=\"style\", <http://shot.[redacted]/build/assets/app-157c9c36.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/Home-a4bcc889.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/Layout-5ef1473e.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/Input-0d5d17c2.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/index-d6de744f.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/index-1bce52b1.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/Button-9a047230.js>; rel=\"modulepreload\""],"X-Powered-By":["PHP/8.3.1"],"Cache-Control":["no-cache, private"]}
127.0.0.1 -  08/Apr/2024:20:57:23 +0000 "GET /index.php" 200
```

---

Browser console log upon home page loading:

```
Blocked loading mixed active content “http://shot.[redacted]/build/assets/app-f4b307cb.css”
shot.[redacted]
Blocked loading mixed active content “http://shot.[redacted]/build/assets/app-157c9c36.js”
shot.[redacted]
Loading failed for the module with source “http://shot.[redacted]/build/assets/app-157c9c36.js”. shot.[redacted]:19:918
Blocked loading mixed active content “http://shot.[redacted]/build/assets/Home-a4bcc889.js”
shot.[redacted]
Loading failed for the module with source “http://shot.[redacted]/build/assets/Home-a4bcc889.js”. shot.[redacted]:19:1010
```

​---

Out of curiosity I tried with Apache too (HTTPS vhost using basic proxypass directives) resulting in same behavior, so I reckon it could be required to review either Nginx server block/Apache vhost config or maybe Caddy itself config...anyhow I'm not that familiar with their syntax so I'm lost here...

P.S.: in case you're wondering, Nginx/Apache HTTPS reverse proxy over Caddy HTTPS throws an error too (different one, anyway).

**Comment by mdshack** [comment]
> After further testing I noticed that issue seems to only occur with Nginx Proxy Manager HTTPS server block on and set as following:
> 
> ![image](https://private-user-images.githubusercontent.com/29974944/320659988-cd4b572e-a94c-49c7-9cb5-cc2ad901555a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDEyNzMsIm5iZiI6MTcxMzE0MDk3MywicGF0aCI6Ii8yOTk3NDk0NC8zMjA2NTk5ODgtY2Q0YjU3MmUtYTk0Yy00OWM3LTljYjUtY2MyYWQ5MDE1NTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAwMjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MjJmOTc2ZjY1MDNmMWNmMjQ2ZTY5NDUwYjZmYzlkNDE1OWZiNDc1ODc4YmMyNmJlMDVkZjA1OTIyODc0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9XU4pPblqc3CExBubGvq2043JLRPlDEkXQZpnzTLYhw)
> 
> Docker startup log:
> 
> ```
>    INFO  Nothing to migrate.  
> Caching application configuration
>    INFO  Configuration cached successfully.  
> [08-Apr-2024 20:56:52] NOTICE: fpm is running, pid 18
> [08-Apr-2024 20:56:52] NOTICE: ready to handle connections
> INF ts=1712609812.873849 msg=using provided configuration config_file=/etc/caddy/Caddyfile config_adapter=
> WRN ts=1712609812.8750105 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile file=/etc/caddy/Caddyfile line=2
> INF ts=1712609812.875975 logger=admin msg=admin endpoint started address=localhost:2019 enforce_origin=false origins=["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]
> WRN ts=1712609812.8762238 logger=http.auto_https msg=server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server server_name=srv0 http_port=80
> INF ts=1712609812.8766096 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc0001d0080
> INF ts=1712609812.8766875 logger=http.log msg=server running name=srv0 protocols=["h1","h2","h3"]
> WRN ts=1712609812.8767629 logger=tls msg=unable to get instance ID; storage clean stamps will be incomplete error=open /data/caddy/instance.uuid: no such file or directory
> INF ts=1712609812.8769293 msg=autosaved config (load with --resume flag) file=/config/caddy/autosave.json
> INF ts=1712609812.8769367 msg=serving initial configuration
> INF ts=1712609812.8819158 logger=tls msg=cleaning storage unit storage=FileStorage:/data/caddy
> INF ts=1712609812.8821518 logger=tls msg=finished cleaning storage units
> ```
> 
> Docker log upon home page loading:
> 
> ```
> INF ts=1712609843.4329681 logger=http.log.access msg=handled request request={"remote_ip":"172.17.0.1","remote_port":"42482","client_ip":"172.17.0.1","proto":"HTTP/1.1","method":"GET","host":"shot.[redacted]","uri":"/","headers":{"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Connection":["close"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Dest":["document"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; rv:122.0) Gecko/20100101 Firefox/122.0"],"Cookie":[],"X-Real-Ip":["192.168.1.1"],"X-Forwarded-For":["192.168.1.1"],"X-Forwarded-Host":["shot.[redacted]"],"Accept-Language":["en-US,en;q=0.5"],"Accept-Encoding":["gzip, deflate, br"],"Sec-Fetch-Site":["none"]}} bytes_read=0 user_id= duration=0.098717598 size=8121 status=200 resp_headers={"Content-Encoding":["gzip"],"Server":["Caddy"],"Vary":["X-Inertia","Accept-Encoding"],"Set-Cookie":[],"Date":["Mon, 08 Apr 2024 20:57:23 GMT"],"Content-Type":["text/html; charset=UTF-8"],"Link":["<http://shot.[redacted]/build/assets/app-f4b307cb.css>; rel=\"preload\"; as=\"style\", <http://shot.[redacted]/build/assets/app-157c9c36.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/Home-a4bcc889.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/Layout-5ef1473e.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/Input-0d5d17c2.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/index-d6de744f.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/index-1bce52b1.js>; rel=\"modulepreload\", <http://shot.[redacted]/build/assets/Button-9a047230.js>; rel=\"modulepreload\""],"X-Powered-By":["PHP/8.3.1"],"Cache-Control":["no-cache, private"]}
> 127.0.0.1 -  08/Apr/2024:20:57:23 +0000 "GET /index.php" 200
> ```
> 
> Browser console log upon home page loading:
> 
> ```
> Blocked loading mixed active content “http://shot.[redacted]/build/assets/app-f4b307cb.css”
> shot.[redacted]
> Blocked loading mixed active content “http://shot.[redacted]/build/assets/app-157c9c36.js”
> shot.[redacted]
> Loading failed for the module with source “http://shot.[redacted]/build/assets/app-157c9c36.js”. shot.[redacted]:19:918
> Blocked loading mixed active content “http://shot.[redacted]/build/assets/Home-a4bcc889.js”
> shot.[redacted]
> Loading failed for the module with source “http://shot.[redacted]/build/assets/Home-a4bcc889.js”. shot.[redacted]:19:1010
> ```
> 
> ​Out of curiosity I tried with Apache too (HTTPS vhost using basic proxypass directives) resulting in same behavior, so I reckon it could be required to review either Nginx server block/Apache vhost config or maybe Caddy itself config...anyhow I'm not that familiar with their syntax so I'm lost here...
> 
> P.S.: in case you're wondering, Nginx/Apache HTTPS reverse proxy over Caddy HTTPS throws an error too (different one, anyway).

Looks like you are getting mixed content errors (hhtp + https), could you set the force https environment variable (`-e FORCE_HTTPS=true`) and see if that fixes your issue? Additionally, could you give the `mdshack/shotshare:1.10.0` release a shot?

Sorry for getting back to you so late.

**Comment by amenolo** [comment]
> could you set the force https environment variable (-e FORCE_HTTPS=true)

Did fix the issue, indeed!

> could you give the mdshack/shotshare:1.10.0 release a shot?

Same issue same fix.

> Sorry for getting back to you so late

Don't worry, we all have a bit of real life somewhere somehow!

**Comment by mdshack** [comment]
> > could you set the force https environment variable (-e FORCE_HTTPS=true)
> 
> Did fix the issue, indeed!
> 
> > could you give the mdshack/shotshare:1.10.0 release a shot?
> 
> Same issue same fix.
> 
> > Sorry for getting back to you so late
> 
> Don't worry, we all have a bit of real life somewhere somehow!

Awesome, thanks for giving that a test and glad it fixed your issue! Going to close this, but if you run into anything else, feel free to open another issue.
