### ISSUE TITLE
default login?

### ISSUE THREAD

**Issue by mptpro** [mdshack/shotshare#76]
I've successully installed SS via Docker and can get to the login page, but I don't know what the default login is?

I have the flag ALLOW_REGISTRATION set to FALSE since this is just for me.

thanks

**Comment by mdshack** [comment]
Without registration enabled you can actually use the `php artisan shotshare:create-user` command from within your shotshare's container, this should allow you to create the first user.

Going to close this but lemme know if you have any issues with this! Additionally, I am planning an installer for v2, which should allow you to do first time setup in the browser.
